image:
  repo: web3f/polkadot-watcher
  # tag: latest

config:
  endpoint: "wss://kusama-rpc.polkadot.io"
  port: 3000
  logLevel: info
  environment: production #it is used also to filter the prometheusrules, i.e. to avoid conflicts between production and staging
  validators: [] #optional
  validatorsFromGit: #optional
    enabled: false
    platform: gitLab
    private: 
      enabled: true
      apiToken: xxx
    network: kusama
    url: http://your.gitlab.domain/api/v4/projects/number/repository/files/accounts.yaml/raw?ref=main

serviceMonitor:
  enabled: true #to be enabled for each instance
  labels:
    group: w3f
    release: prometheus-operator

prometheusRules:
  enabled: false #if you have multiple instances, enabled it just once to avoid duplicated alerts
  labels:
    app: w3f
  origin: cluster  
  producerStall: true 
  changed: true

resources:
  requests:
    cpu: "100m"
    memory: "500Mi"
  limits:
    cpu: "100m"
    memory: "500Mi"
